# Generated by Django 5.2.8 on 2025-11-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_family_alter_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="family",
            index=models.Index(fields=["code"], name="accounts_fa_code_7c8c17_idx"),
        ),
    ]
