# Generated by Django 5.2.8 on 2025-11-13 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_family_points_family_accounts_fa_code_7c8c17_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("progress", models.FloatField(default=0.0)),
                ("points", models.PositiveIntegerField(default=0)),
                ("completed_items", models.JSONField(blank=True, default=list)),
                ("total_items", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "family",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character",
                        to="accounts.family",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character",
                "verbose_name_plural": "Characters",
                "indexes": [
                    models.Index(
                        fields=["family"], name="main_charac_family__74eb6b_idx"
                    ),
                    models.Index(
                        fields=["-last_updated"], name="main_charac_last_up_e02581_idx"
                    ),
                    models.Index(
                        fields=["points"], name="main_charac_points_428538_idx"
                    ),
                ],
            },
        ),
    ]
