# Generated by Django 5.2.8 on 2025-11-11 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_family_points_family_accounts_fa_code_7c8c17_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_questions",
                        to="accounts.family",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_questions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="지정 대상(선택). None이면 가족 전체 대상",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_questions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Question",
                "verbose_name_plural": "Custom Questions",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CustomQAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("is_anonymous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="customqa.customq",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customq_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="customqa.customqanswer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customq_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="customq",
            index=models.Index(
                fields=["family", "created_at"], name="customqa_cu_family__2e58ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customq",
            index=models.Index(
                fields=["to_user"], name="customqa_cu_to_user_2650c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customqanswer",
            index=models.Index(
                fields=["question", "user"], name="customqa_cu_questio_c51b51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customqanswer",
            index=models.Index(
                fields=["created_at"], name="customqa_cu_created_1cea90_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customqanswer",
            constraint=models.UniqueConstraint(
                fields=("question", "user"), name="uq_answer_per_user_per_customq"
            ),
        ),
        migrations.AddIndex(
            model_name="reply",
            index=models.Index(
                fields=["answer", "created_at"], name="customqa_re_answer__3ab503_idx"
            ),
        ),
    ]
