# Generated by Django 5.2.8 on 2025-11-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customqa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customq',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='질문자 익명 여부'),
        ),
        migrations.AddField(
            model_name='customq',
            name='is_public',
            field=models.BooleanField(default=True, help_text='질문 공개 여부'),
        ),
    ]
