# Generated by Django 5.2.8 on 2025-11-11 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_family_points_family_accounts_fa_code_7c8c17_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Admin Question",
                "verbose_name_plural": "Admin Question",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "created_at"],
                        name="adminqa_adm_is_acti_e97030_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FamilyQuestionInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("CLOSED", "Closed")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_current", models.BooleanField(default=True)),
                ("exp", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_q",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_instances",
                        to="adminqa.adminq",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_q_instances",
                        to="accounts.family",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AdminQAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("is_anonymous", models.BooleanField(default=False)),
                ("is_ancestral", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_q_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family_q_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="adminqa.familyquestioninstance",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="familyquestioninstance",
            index=models.Index(
                fields=["family", "is_current"], name="adminqa_fam_family__d2455f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="familyquestioninstance",
            index=models.Index(
                fields=["admin_q", "status"], name="adminqa_fam_admin_q_9b8289_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="familyquestioninstance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("family",),
                name="uq_family_current_adminq_instance",
            ),
        ),
        migrations.AddIndex(
            model_name="adminqanswer",
            index=models.Index(
                fields=["family_q_instance", "user"],
                name="adminqa_adm_family__8a0fc1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adminqanswer",
            index=models.Index(
                fields=["created_at"], name="adminqa_adm_created_31d29f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="adminqanswer",
            constraint=models.UniqueConstraint(
                fields=("family_q_instance", "user"),
                name="uq_answer_per_user_per_instance",
            ),
        ),
    ]
