# Generated by Django 5.2.8 on 2025-11-07 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_family_alter_user_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MissionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='missions/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('completedDate', models.DateField(blank=True, null=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missionInstances', to='accounts.family')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='mission.mission')),
            ],
            options={
                'ordering': ['-completedDate'],
            },
        ),
        migrations.CreateModel(
            name='MissionInstanceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isSubmitted', models.BooleanField(default=False)),
                ('missionInstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userMissions', to='mission.missioninstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userMissionInstances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('missionInstance', 'user'), name='uqMissionInstanceUser')],
            },
        ),
    ]
