# Generated by Django 5.2.8 on 2025-11-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missioninstance',
            name='image',
        ),
        migrations.AddField(
            model_name='missioninstanceuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='missions/'),
        ),
    ]
